#!/usr/bin/env python3
"""Generate byte-verified native variants of SMA3 RAM code.

GameInitMain copies 0x80 words from one of these ROM sources to 03007040.
Each variant has its own symbol prefix so aliased RAM addresses stay distinct.
"""
import argparse
from pathlib import Path
import subprocess
ROOT = Path(__file__).resolve().parents[1]
HBLANK_SOURCES = (0x0810C10C,0x0810C178,0x0810C264,0x0810C2F0,0x0810C37C,0x0810C408,0x0810C494,0x0810C520,0x0810D264)
VARIANTS = [(f'{s:08X}', 0x03007040, s, 0x200) for s in HBLANK_SOURCES]
# StoryIntroToadies.asm: 0802F8E2..0802F90A copies this routine after
# 335C8 without allocating the text routine. Observed RAM destination 03004054.
# The alternate text-intro path (0802FE82..0802FEDA) places it at 03004110.
VARIANTS += [('intro_03004054', 0x03004054, 0x08033224, 0x3A4)]
p = argparse.ArgumentParser()
p.add_argument('--rom', required=True, type=Path)
p.add_argument('--recompiler', type=Path, default=ROOT.parent/'gbarecomp/build/gba_recompile')
a = p.parse_args()
for ident, ram, source, size in VARIANTS:
    prefix = f'ov{ident}_'
    out = ROOT/'generated-overlays'/ident
    out.mkdir(parents=True,exist_ok=True)
    config = out/'config.toml'
    config.write_text(f'''[program]
name="SMA3 overlay {ident}"
id="{prefix}"
load_address=0x08000000
size=0x00400000
entry_pc=0x{ram:08X}
speculative_literal_harvest=false
static_resume_all=true
codegen_shards=2
[identity]
sha1="7352d2bd064d9ebaec579e264228aa21c7345b80"
[[code_copy]]
runtime_start=0x{ram:08X}
source_start=0x{source:08X}
size=0x{size:X}
[[extra_func]]
addr=0x{ram:08X}
mode="thumb"
name="overlay_entry"
''')
    subprocess.run([str(a.recompiler.resolve()),'--rom',str(a.rom.resolve()),'--config',str(config),'--out',str(out),'--output-prefix',prefix,'--codegen-shards','2'],check=True)
s = '''// Generated by tools/generate_overlays.py. Do not hand edit.
#include "runtime_arm.h"
#include "runtime_bus_bridge.h"
#include "gba_bus.h"
#include <cstdint>
#include <cstring>
struct DispatchEntry { uint32_t addr; uint8_t thumb; uint8_t resume; void (*fn)(void); };
'''
for ident, ram, source, size in VARIANTS:
    s += f'extern "C" const DispatchEntry ov{ident}_kDispatchTable[];\nextern "C" const unsigned ov{ident}_kDispatchTableLen;\n'
s += '''int sma3_overlay_dispatch(uint32_t pc, int thumb) {
    if (pc < 0x03000000 || pc >= 0x03008000 || !thumb) return 0;
    auto* bus = gbarecomp::active_bus();
    if (!bus || bus->rom_size() != 0x400000) return 0;
    struct Variant { uint32_t ram, source, size; const DispatchEntry* table; const unsigned* count; };
    const Variant variants[] = {
'''
for ident, ram, source, size in VARIANTS:
    s += f'        {{0x{ram:08X}, 0x{source:08X}, 0x{size:X}, ov{ident}_kDispatchTable, &ov{ident}_kDispatchTableLen}},\n'
s += '''    };
    for (const auto& variant : variants) {
        if (pc < variant.ram || pc - variant.ram >= variant.size) continue;
        if (std::memcmp(bus->iwram_ptr() + variant.ram - 0x03000000,
                        bus->rom_ptr() + variant.source - 0x08000000, variant.size)) continue;
        unsigned lo = 0, hi = *variant.count;
        while (lo < hi) {
            const unsigned mid = lo + (hi - lo) / 2;
            const auto& entry = variant.table[mid];
            if (entry.addr < pc || (entry.addr == pc && entry.thumb < thumb)) lo = mid + 1;
            else hi = mid;
        }
        if (lo == *variant.count) return 0;
        const auto& entry = variant.table[lo];
        if (entry.addr != pc || entry.thumb != thumb) return 0;
        g_runtime_resume_pc = entry.resume ? pc : 0;
        entry.fn();
        return 1;
    }
    return 0;
}
'''
(ROOT/'src/overlay_dispatch.cpp').write_text(s)
