// Generated by tools/generate_overlays.py. Do not hand edit.
#include "runtime_arm.h"
#include "runtime_bus_bridge.h"
#include "gba_bus.h"
#include <cstdint>
#include <cstring>
struct DispatchEntry { uint32_t addr; uint8_t thumb; uint8_t resume; void (*fn)(void); };
extern "C" const DispatchEntry ov0810C10C_kDispatchTable[];
extern "C" const unsigned ov0810C10C_kDispatchTableLen;
extern "C" const DispatchEntry ov0810C178_kDispatchTable[];
extern "C" const unsigned ov0810C178_kDispatchTableLen;
extern "C" const DispatchEntry ov0810C264_kDispatchTable[];
extern "C" const unsigned ov0810C264_kDispatchTableLen;
extern "C" const DispatchEntry ov0810C2F0_kDispatchTable[];
extern "C" const unsigned ov0810C2F0_kDispatchTableLen;
extern "C" const DispatchEntry ov0810C37C_kDispatchTable[];
extern "C" const unsigned ov0810C37C_kDispatchTableLen;
extern "C" const DispatchEntry ov0810C408_kDispatchTable[];
extern "C" const unsigned ov0810C408_kDispatchTableLen;
extern "C" const DispatchEntry ov0810C494_kDispatchTable[];
extern "C" const unsigned ov0810C494_kDispatchTableLen;
extern "C" const DispatchEntry ov0810C520_kDispatchTable[];
extern "C" const unsigned ov0810C520_kDispatchTableLen;
extern "C" const DispatchEntry ov0810D264_kDispatchTable[];
extern "C" const unsigned ov0810D264_kDispatchTableLen;
extern "C" const DispatchEntry ovintro_03004054_kDispatchTable[];
extern "C" const unsigned ovintro_03004054_kDispatchTableLen;
int sma3_overlay_dispatch(uint32_t pc, int thumb) {
    if (pc < 0x03000000 || pc >= 0x03008000 || !thumb) return 0;
    auto* bus = gbarecomp::active_bus();
    if (!bus || bus->rom_size() != 0x400000) return 0;
    struct Variant { uint32_t ram, source, size; const DispatchEntry* table; const unsigned* count; };
    const Variant variants[] = {
        {0x03007040, 0x0810C10C, 0x200, ov0810C10C_kDispatchTable, &ov0810C10C_kDispatchTableLen},
        {0x03007040, 0x0810C178, 0x200, ov0810C178_kDispatchTable, &ov0810C178_kDispatchTableLen},
        {0x03007040, 0x0810C264, 0x200, ov0810C264_kDispatchTable, &ov0810C264_kDispatchTableLen},
        {0x03007040, 0x0810C2F0, 0x200, ov0810C2F0_kDispatchTable, &ov0810C2F0_kDispatchTableLen},
        {0x03007040, 0x0810C37C, 0x200, ov0810C37C_kDispatchTable, &ov0810C37C_kDispatchTableLen},
        {0x03007040, 0x0810C408, 0x200, ov0810C408_kDispatchTable, &ov0810C408_kDispatchTableLen},
        {0x03007040, 0x0810C494, 0x200, ov0810C494_kDispatchTable, &ov0810C494_kDispatchTableLen},
        {0x03007040, 0x0810C520, 0x200, ov0810C520_kDispatchTable, &ov0810C520_kDispatchTableLen},
        {0x03007040, 0x0810D264, 0x200, ov0810D264_kDispatchTable, &ov0810D264_kDispatchTableLen},
        {0x03004054, 0x08033224, 0x3A4, ovintro_03004054_kDispatchTable, &ovintro_03004054_kDispatchTableLen},
    };
    for (const auto& variant : variants) {
        if (pc < variant.ram || pc - variant.ram >= variant.size) continue;
        if (std::memcmp(bus->iwram_ptr() + variant.ram - 0x03000000,
                        bus->rom_ptr() + variant.source - 0x08000000, variant.size)) continue;
        unsigned lo = 0, hi = *variant.count;
        while (lo < hi) {
            const unsigned mid = lo + (hi - lo) / 2;
            const auto& entry = variant.table[mid];
            if (entry.addr < pc || (entry.addr == pc && entry.thumb < thumb)) lo = mid + 1;
            else hi = mid;
        }
        if (lo == *variant.count) return 0;
        const auto& entry = variant.table[lo];
        if (entry.addr != pc || entry.thumb != thumb) return 0;
        g_runtime_resume_pc = entry.resume ? pc : 0;
        entry.fn();
        return 1;
    }
    return 0;
}
